### PR TITLE
Dashboard Skeleton Built

### PR DESCRIPTION
**Pull request by aaronfife**
## Description
built the shell/skeleton for the dashboard/feed

## How to test
on the nav bar click the very last button that looks like a home and the dashboard skeleton will be populated

## Notes
will start dynamically populating the feed - need to create dummy data for the feed next

## Issue tracking
https://trello.com/c/ywsakMfb/37-dashboard-skeleton

## Current Image
Screen Shot 2021-12-30 at 4 19 21 PM

### CODE REVIEW

**Review by surekhaw — APPROVED** [review]
looks great!

**Review by shabbyblue16 — COMMENTED** [review]
Looks good already!

**Review by Laweeza — APPROVED** [review]
Looks great Aaron!

**Comment by Laweeza** [comment]
[dashboard skeleton](https://trello.com/c/ywsakMfb/37-dashboard-skeleton)

**Pull request merged**
