### PR TITLE
Added qr code to pr comments

### PR DESCRIPTION
**Pull request by shabbyblue16**
## Description
I wrote an additional script to the .yml file that publishes our app to an Expo CDN and then comments a QR code into the PR. This makes it easier to test the app manually on code review. 

## How to test
On each PR scan the QR code and make sure it opens on your phone's Expo Go app.

## Notes
- There isn't an easy way to test this locally so there may be multiple PRs regarding this issue until I get it right.
- Also added dependency caching to increase the speed of the CI checks

### CODE REVIEW

**Comment by shabbyblue16** [comment]
Able to merge now

**Review by Laweeza — APPROVED** [review]

**Comment by shabbyblue16** [comment]
Expo QR
Published to https://exp.host/@heartbleed/quick-bagel?release-channel=pr13

**Comment by shabbyblue16** [comment]
Expo QR
Published to https://exp.host/@heartbleed/whimsical?release-channel=pr13

**Comment by Laweeza** [comment]
> Expo QR Published to https://exp.host/@heartbleed/whimsical?release-channel=pr13

up and running and looks great. my pixel 2 just always cuts off the navbar in the dashboard when i log in lol

**Review by aaronfife — APPROVED** [review]

**Pull request merged**
